version: '3'

services:
    tailscale:
        image: jonoh/tailscale
        volumes:
            - /host/path/data:/var/lib/tailscale
        devices:
            - /dev/net/tun:/dev/net/tun
        net: host
        privileged: true
        environment:
            - AUTH_KEY=ts123123
