name: build docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  # renovate: datasource=github-releases depName=tailscale/tailscale
  TAILSCALE_VERSION: v1.14.4
  DOCKER_REPO: jonoh/tailscale

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Fetch tailscale code, read version, prepare Dockerfile
        id: get_tailscale
        env:
          TAILSCALE_VERSION: ${{ env.TAILSCALE_VERSION }}
        run: ./pre-build.sh

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: tailscale
          file: ./tailscale/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args: |
            VERSION_LONG=${{ steps.get_tailscale.outputs.VERSION_LONG }}
            VERSION_SHORT=${{ steps.get_tailscale.outputs.VERSION_SHORT }}
            VERSION_GIT_HASH=${{ steps.get_tailscale.outputs.VERSION_GIT_HASH }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: "${{ env.DOCKER_REPO }}:${{ steps.get_tailscale.outputs.VERSION_SHORT }},${{ env.DOCKER_REPO }}:latest"

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
